import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sedat Taşkıran | Web Page</title>
        <meta name="description" content="Generated by Sedat Taşkıran setas" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-center text-8xl text-white ">Hello!</h1>

        <p className="text-center text-3xl text-white ">
          Web3 enthusiast, self-motivated, proactive, detailed-oriented,
          adaptive, responsible, and committed engineer eager to learn. Having
          experience of testing, designing, implementing, and delivering web
          applications using variety programming languages and technologies.
        </p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
